Added an admin column to users and a callback method is_admin? to the…
ctti-clinicaltrials/aact-admin pull request #123
Opened 2021-11-04 17:10 UTC by Javier-Jimenez-18

… application controller.

2021-11-23 16:12 UTC, micronix requested changes
Test the app with an admin user and a non-admin user

2021-12-17 19:53 UTC, Javier-Jimenez-18 commented on app/controllers/application_controller.rb
> +  before_action :is_admin?
Removed is_admin? from application controller.
Tested the app with an admin user and non-admin user.

2021-12-17 20:10 UTC, Javier-Jimenez-18 commented
<img width="1280" alt="Screen Shot 2021-12-16 at 11 42 12 AM" src="https://user-images.githubusercontent.com/81119399/146602002-c3714536-eed6-40f3-9c69-6c646095a822.png">
<img width="1280" alt="Screen Shot 2021-12-16 at 11 43 37 AM" src="https://user-images.githubusercontent.com/81119399/146602013-098dc951-9574-4293-a45b-9e41d6ebfad7.png">
<img width="1280" alt="Screen Shot 2021-12-17 at 8 31 29 AM" src="https://user-images.githubusercontent.com/81119399/146602014-b7c5b675-de92-4cd6-8c03-fbf1b2cb54a5.png">

2021-12-18 20:35 UTC, crystal-wb approved these changes
Looks good. Nice work

2021-12-18 20:37 UTC, merged