Feat/aact 245 release notes
ctti-clinicaltrials/aact-admin pull request #130
Opened 2021-11-20 17:21 UTC by kholtzman5610

- Added current released notes
- Removed old released notes

2021-11-23 16:15 UTC, micronix requested changes
remove the changes on schema.sql other than that it looks good

2021-12-08 20:11 UTC, crystal-wb requested changes
I had some notes about the wording of the release notes. Otherwise the pull quest looks fine. Please let me know if you have any questions.

2021-12-08 20:11 UTC, crystal-wb commented on app/views/release_notes/_v4.7.1.html.erb
> + <h3>AACT 4.7.1 <i>(September 18, 2021)</i></h3>
This release has incorrect notes. They should be:

- Renamed ctgov_beta_group_code to ctgov_group_code
- Added mesh_type column for browse_conditions and browse_interventions tables
- Edited code to save more MeSH types to the database
- changed factory_girl to the factory_bot gem
- added Airbrake for tracking errors
- Added database explanation and visualization to the README
- Edited how the downcase mesh terms are created so they would be updated regularly
- Edited the way the loads are run to better switch between schemas
- Added environmental variables for the ctgov_beta schema and database

Remove the current release notes from this view and add the ones I listed above instead

2021-12-08 20:11 UTC, crystal-wb commented on app/views/release_notes/_v5.0.2.1.html.erb
> + </ul>
all these need to be reworded

- "Added messages to data_verification method to let you know what is happening"
- "Fixed Util::Updater tests"
- "Setup code to create flat files for beta"
- "Setup code to create snapshots for beta"
- "Added an example connections.yml file"
- "Added a script that compares between schemas tables with that only have one occurrence of each nct_id"

2021-12-08 20:11 UTC, crystal-wb commented on app/views/release_notes/_v6.0.0.html.erb
> + <p>The study_statistics endpoint is used to validate data in our database</p>
Needs rewording too

- "Added Airbrake notifications to StudyJsonRecord model"
- "Setup code to check study statistics each time a load is done"
- "Setup code to only use the Beta API when doing a load"
- "Setup code to compare our data for the Beta API study statistics endpoint for data validation purposes"

2021-12-18 20:34 UTC, crystal-wb requested changes
Looks good overall. I requested one minor edit.

2021-12-18 20:34 UTC, crystal-wb commented on app/views/release_notes/_v5.0.2.1.html.erb
> + <h5>Release notes - AACT - Version aact-core-5.0.2</h5>
This can remove this line
`<h5>Release notes - AACT - Version aact-core-5.0.2</h5>`
 since the version is given above

2021-12-22 16:09 UTC, micronix approved these changes

2021-12-22 16:10 UTC, merged