Changed logo on main header
ctti-clinicaltrials/aact-admin pull request #159
Opened 2022-03-08 23:34 UTC by kholtzman5610

- Changed the height to 100 and width 200

2022-03-08 23:36 UTC, kholtzman5610 commented
### **User Login**
![User-Login](https://user-images.githubusercontent.com/50157150/157343837-84c3b3d6-239b-46fa-874d-8d1dcd3c8ec9.jpg)

### **No User Login**
![No-User-Login](https://user-images.githubusercontent.com/50157150/157343895-45c5520d-bb94-44c5-b1e6-00b7937d7bc0.jpg)

2022-03-22 01:30 UTC, Javier-Jimenez-18 approved these changes
User logged in/logged out home page looks good to me. Great job.

Missing http://localhost:3000/users screenshot when logged in as an admin.

2022-03-23 02:57 UTC, micronix commented
@kholtzman5610 there are no screenshots of the users page and I also don't see the changes we made to the users page. Does that still need to be commited?

2022-03-23 16:15 UTC, kholtzman5610 commented
@micronix @Javier-Jimenez-18 screenshot fixed and updated code fixed.

2022-03-25 05:20 UTC, Javier-Jimenez-18 approved these changes
looks good.

2022-03-25 15:19 UTC, micronix requested changes
Remove/update package versions

2022-03-25 15:19 UTC, micronix commented on app/views/layouts/application.html.erb
> +
1. Remove the old bootstrap version
2. Remove the old jquery version
3. Update the bootstrap-table version from 1.8.1 to the latest one https://cdnjs.com/libraries/bootstrap-table

2022-04-14 17:11 UTC, micronix approved these changes
Looks good

2022-04-14 17:11 UTC, merged