Fixed the structure of the footer using bootstrap grid system
ctti-clinicaltrials/aact-admin pull request #160
Opened 2022-03-11 16:23 UTC by kholtzman5610

- Added a padding 10px line 91 in app/assets/stylesheets/includes/footer.scss
- Added bootstap grid system [line 4-19] in app/views/includes/_main_footer.html.erb

2022-03-11 16:25 UTC, kholtzman5610 commented
![footer](https://user-images.githubusercontent.com/50157150/157907206-69ec3db7-8538-4b88-8a75-934cce4fafe9.jpg)

2022-03-14 20:54 UTC, micronix requested changes

2022-03-14 20:54 UTC, micronix commented on app/views/includes/_main_footer.html.erb
>    <div class="footerBar comtainer ">
Hey @kholtzman5610 the class `comtainer` looks like mispelling. Can you try removing it and see if it still looks ok? If it does let's just remove that class.

2022-03-16 15:21 UTC, micronix approved these changes
Looks good

2022-03-16 15:21 UTC, merged