Revised the Download page UI
ctti-clinicaltrials/aact-admin pull request #233
Opened 2022-10-05 23:38 UTC by ievgend2

2022-10-06 00:47 UTC, Javier-Jimenez-18 approved these changes
Looks good. Any screenshots to see the final views? I'm sure Ramiro will approve it when he sees the changes tomorrow (if he has time to meet).

2022-10-06 15:54 UTC, kholtzman5610 approved these changes
Styling looks better on all just add a few screenshots to show the deference otherwise everything is great.

2022-10-06 18:21 UTC, micronix requested changes
I think it all looks good, the only thing is that we don't want to completly remove the html for the downloads on each page snapshots, pipefiles, covid but we can hide them right now.

2022-10-06 18:21 UTC, micronix commented on app/views/pages/covid_19.html.erb
>      <p>For AACT database users, a table called "covid_19_studies" containing the 68 columns from the spreadsheet, is now included within AACT.</p>
Hey @ievgend2 there are some users that scrape this page for the links, could you still include this html? You can hide it using css like `display: none`

2022-10-11 23:35 UTC, ievgend2 commented
New Layout:
![image](https://user-images.githubusercontent.com/66342665/195217296-3f05fa2e-fcf0-4bf6-a534-b56ef088f474.png)

2022-10-12 15:23 UTC, merged