AACT-437: As a user I should be able to "view" the query
ctti-clinicaltrials/aact-admin pull request #246
Opened 2022-11-02 18:07 UTC by Javier-Jimenez-18

- Added the show action to the SavedQueriesController. 
- Created the show view page:

<img width="1280" alt="Screen Shot 2022-11-02 at 11 03 32 AM" src="https://user-images.githubusercontent.com/81119399/199567677-f3437517-bc8d-4067-99c3-5d0b82db0e2f.png">

2022-11-07 17:18 UTC, micronix requested changes
Some small changes

2022-11-07 17:18 UTC, micronix commented on app/controllers/saved_queries_controller.rb
> +    if @saved_query.save
We want to add the currently logged in user
```ruby
@saved_query.user_id = current_user.id
```

2022-11-07 17:18 UTC, micronix commented on app/views/saved_queries/_form.html.erb
> +    </div>
Missing `public` field

2022-11-07 17:18 UTC, micronix commented on app/views/saved_queries/index.html.erb
> +            <td><%= query.user %></td>
put the user name instead of the user object

2022-11-11 00:56 UTC, Javier-Jimenez-18 commented
- Updated create action. 
- Updated index view page to show username. 
- Updated _form view page to add a checkbox to make SQL query public. 
- Modified shared.scss stylesheet to remove label padding.

<img width="1280" alt="Screen Shot 2022-11-10 at 4 26 03 PM" src="https://user-images.githubusercontent.com/81119399/201237273-d039d1a5-efce-44e8-8ea1-ea9db86dcae4.png">

<img width="1280" alt="Screen Shot 2022-11-10 at 4 26 44 PM" src="https://user-images.githubusercontent.com/81119399/201237286-ce8ecdb0-d63f-4fb1-8453-7a4868f5f067.png">

<img width="1280" alt="Screen Shot 2022-11-10 at 4 27 50 PM" src="https://user-images.githubusercontent.com/81119399/201237307-234294ce-c4d1-4b93-b4bb-daa8d8c7f7f0.png">

<img width="1280" alt="Screen Shot 2022-11-10 at 4 28 27 PM" src="https://user-images.githubusercontent.com/81119399/201237330-33e14edc-3481-4f2d-81f8-389529831562.png">

2022-11-20 00:28 UTC, Javier-Jimenez-18 commented
In the Saved Queries show page, displayed “SQL Query is public” or “SQL Query is not public” (User clicks corresponding checkbox):

<img width="1280" alt="Screen Shot 2022-11-19 at 4 21 14 PM" src="https://user-images.githubusercontent.com/81119399/202876956-14369f92-2c1a-425f-a21d-4ee04b837b7d.png">

<img width="1280" alt="Screen Shot 2022-11-19 at 4 21 38 PM" src="https://user-images.githubusercontent.com/81119399/202876959-92a07bd7-8a5c-4dff-bf74-584414f81644.png">

2022-11-20 01:49 UTC, ievgend2 approved these changes
Looks Good

2022-12-09 17:38 UTC, closed without merging