AACT-439: As a user I should be able to edit a query that I created
ctti-clinicaltrials/aact-admin pull request #250
Opened 2022-12-06 00:08 UTC by Javier-Jimenez-18

- Added a button/link on the show page to /queries/:id/edit

<img width="1280" alt="Screen Shot 2022-12-05 at 3 36 13 PM" src="https://user-images.githubusercontent.com/81119399/205771808-ae280b28-4231-4761-99c8-2703de6624fc.png">

<img width="1280" alt="Screen Shot 2022-12-05 at 3 55 44 PM" src="https://user-images.githubusercontent.com/81119399/205771839-00d4c304-8f6a-4540-ad9a-176c7d1dfb24.png">

- Created an edit action in the Saved Queries controller that loads the query that we are editing. It checks to see if the currently logged in user created the query and if they did create it, then show the edit page.

<img width="1280" alt="Screen Shot 2022-12-05 at 3 40 26 PM" src="https://user-images.githubusercontent.com/81119399/205772874-e64b60f0-8bd9-4816-a22d-99a3600910b8.png">

<img width="1280" alt="Screen Shot 2022-12-05 at 3 40 42 PM" src="https://user-images.githubusercontent.com/81119399/205772915-7d46b4a3-b00a-4799-b3e0-4f2b68a6fa77.png">

- If the logged in user did not create the query, it redirects them to the index page for the saved queries and adds a flash message saying “You do not have permission to edit that query”. 

<img width="1280" alt="Screen Shot 2022-12-05 at 3 43 33 PM" src="https://user-images.githubusercontent.com/81119399/205773152-1fb552b5-90d3-4baf-b0ee-23e999d4111d.png">

<img width="1280" alt="Screen Shot 2022-12-05 at 3 44 18 PM" src="https://user-images.githubusercontent.com/81119399/205773185-5edc61e3-3572-4fca-b8b5-51d486d876a5.png">

- Updated SavedQueriesController RSpec Controller test file.

<img width="1280" alt="Screen Shot 2022-12-05 at 3 17 53 PM" src="https://user-images.githubusercontent.com/81119399/205773335-6a184f25-51dd-43de-9f64-e3b8d2d51280.png">

- The SavedQueriesController RSpec Request test file has some issues and will be investigated further.

2022-12-08 19:21 UTC, kholtzman5610 approved these changes
Good job with the test cases and screenshots. Looks good

2022-12-09 17:06 UTC, micronix requested changes
Looks good, just some small changes

2022-12-15 01:54 UTC, Javier-Jimenez-18 commented
- Modified SavedQueriesController index, edit, update, and destroy actions to check to see if the currently logged in user created the query. If not, it renders a not found error (404) page.
- Index shows all the queries that belong to the currently logged in user & all the queries that don't belong to the user and have Public set true. 

<img width="1280" alt="Screen Shot 2022-12-14 at 4 58 56 PM" src="https://user-images.githubusercontent.com/81119399/207753221-2897e1fa-5f44-4e1a-b3e8-fb224fd2437d.png">

<img width="1280" alt="Screen Shot 2022-12-14 at 4 59 57 PM" src="https://user-images.githubusercontent.com/81119399/207753250-abd07d0f-2b9e-4c34-8607-898f3ac8b5ce.png">

<img width="1280" alt="Screen Shot 2022-12-14 at 5 04 41 PM" src="https://user-images.githubusercontent.com/81119399/207753275-02d25b1a-c988-4dbf-9506-8b9506227f7a.png">

<img width="1280" alt="Screen Shot 2022-12-14 at 5 04 51 PM" src="https://user-images.githubusercontent.com/81119399/207753289-b1c406a5-115f-4b6c-baf5-85cba3530d89.png">

- Updated RSpec Controller test file. 

<img width="1280" alt="Screen Shot 2022-12-14 at 4 56 05 PM" src="https://user-images.githubusercontent.com/81119399/207753355-bd9a55ff-e277-41df-bb55-18bdcbb5e3b6.png">

- Updated RSpec Request test file. Each test case PASSES when run individually. Will have to investigate further to see why the test file has FAILURES when all test cases are run together.

- Cleaned up and refactored code.

2022-12-15 02:02 UTC, Javier-Jimenez-18 commented
All saved queries that are public, or that belong to the current user are shown in the index page. But, the current user can't go to the show page of another user's query, not_found (404) gets rendered. Is this what we want? I thought the current user can go to the show page of any public query and be able to at least run the SQL, but not be able to edit or delete the query. Is this correct?

2022-12-16 10:12 UTC, Javier-Jimenez-18 commented
- Modified Show, Edit, Update, and Destroy actions for the SavedQueriesController. Allowed a logged-in user to view the show page of another user's public query. 

<img width="1280" alt="Screen Shot 2022-12-16 at 1 51 36 AM" src="https://user-images.githubusercontent.com/81119399/208074970-6bf232f3-ffa8-44fc-8f4c-42320623123c.png">

<img width="1280" alt="Screen Shot 2022-12-16 at 1 52 08 AM" src="https://user-images.githubusercontent.com/81119399/208075007-e5f8f5b6-da6d-4280-a7d6-427c6a66d4c8.png">

<img width="1280" alt="Screen Shot 2022-12-16 at 1 53 31 AM" src="https://user-images.githubusercontent.com/81119399/208075026-bd5e7269-815b-45f4-a377-bc45fe2bdf23.png">

<img width="1280" alt="Screen Shot 2022-12-16 at 1 55 12 AM" src="https://user-images.githubusercontent.com/81119399/208075069-ea731a2d-ed6c-4c5b-bca4-7b13da4bcc3a.png">

<img width="1280" alt="Screen Shot 2022-12-16 at 1 55 25 AM" src="https://user-images.githubusercontent.com/81119399/208075093-0728d943-775b-464d-8cad-1a17d3271731.png">

<img width="1280" alt="Screen Shot 2022-12-16 at 1 56 57 AM" src="https://user-images.githubusercontent.com/81119399/208075116-28e1004f-4223-4d00-ae25-837e0fe050cb.png">

<img width="1280" alt="Screen Shot 2022-12-16 at 1 57 43 AM" src="https://user-images.githubusercontent.com/81119399/208075139-39da4ddd-ff29-4dea-a4e4-aa4e57ef31f5.png">

- Modified and updated the RSpec Controller test file.

<img width="1280" alt="Screen Shot 2022-12-16 at 1 50 22 AM" src="https://user-images.githubusercontent.com/81119399/208075234-bf70f15f-fd9a-4d0e-a3f4-fc7c801e0084.png">

- Modified and updated the RSpec Request test file. Each test case PASSES when run individually. Will have to investigate further to see why the test file has FAILURES when all test cases are run together.

2022-12-16 16:26 UTC, micronix requested changes
The `show` action should have the logic to allow any user to see it if it is public or the user that created it is trying to see it.

The `edit`, `update` & `destroy` should only be accessible to the user that created it.

2022-12-16 16:28 UTC, micronix requested changes

2022-12-16 16:28 UTC, micronix commented on app/views/saved_queries/show.html.erb
> +          <%= link_to 'Delete', saved_query_path(@saved_query), :class => "btn btn-danger btn-sm", :method => :delete, data: { confirm: 'Are you sure?' } %>
Only show the buttons if the logged in user is the one that created the saved query

2022-12-16 18:18 UTC, Javier-Jimenez-18 commented
- Modified Show, Edit, and Destroy actions in the SavedQueriesController. 

- Modified Show view page to only show edit and delete buttons for the User that created the query.

<img width="1280" alt="Screen Shot 2022-12-16 at 10 12 29 AM" src="https://user-images.githubusercontent.com/81119399/208163182-9e808359-7317-46cc-9749-a414f07446d3.png">

<img width="1280" alt="Screen Shot 2022-12-16 at 10 16 52 AM" src="https://user-images.githubusercontent.com/81119399/208163199-d3e4c0c5-f675-4b2d-b3a0-bf44150ba566.png">

<img width="1280" alt="Screen Shot 2022-12-16 at 10 13 01 AM" src="https://user-images.githubusercontent.com/81119399/208163217-065692ee-32e1-4dcc-89f8-033d70a95d2d.png">

<img width="1280" alt="Screen Shot 2022-12-16 at 10 13 37 AM" src="https://user-images.githubusercontent.com/81119399/208163251-d6c61e16-a635-4e87-8d53-3427ce00edc8.png">

<img width="1280" alt="Screen Shot 2022-12-16 at 9 15 38 AM" src="https://user-images.githubusercontent.com/81119399/208163285-e99250e8-6226-4347-9cfb-43050cf6ba71.png">

2022-12-22 16:21 UTC, merged