AACT-474: Create CRUD for Background Jobs
ctti-clinicaltrials/aact-admin pull request #267
Opened 2023-03-14 23:26 UTC by Javier-Jimenez-18

An Admin User can see all of the background jobs created in the index page 
(newuser is an Admin):

<img width="1280" alt="Screen Shot 2023-03-14 at 2 59 19 PM" src="https://user-images.githubusercontent.com/81119399/225153803-46eeffa3-b495-4d99-8e31-ec6259f321a3.png">

An Admin User can see all of the background job details in the show page 
(newuser is an Admin):

<img width="1280" alt="Screen Shot 2023-03-14 at 3 00 14 PM" src="https://user-images.githubusercontent.com/81119399/225156924-fa2c8a6e-0724-4734-b630-4c2744e1c89e.png">

<img width="1280" alt="Screen Shot 2023-03-14 at 3 00 54 PM" src="https://user-images.githubusercontent.com/81119399/225156953-f9e31ead-0230-4fe4-ac2b-77d0941332b6.png">

A non Admin User can only see the background jobs that they created in the index and show page 
(testuser is not an Admin):

<img width="1280" alt="Screen Shot 2023-03-14 at 3 17 33 PM" src="https://user-images.githubusercontent.com/81119399/225155728-3077341e-3846-41da-8588-f155b741595c.png">

<img width="1280" alt="Screen Shot 2023-03-14 at 3 18 06 PM" src="https://user-images.githubusercontent.com/81119399/225157480-5a472098-38e3-4c39-aa96-472d2462f340.png">

A non Admin User can delete their background jobs that are in the "pending" state 
(testuser is not an Admin):

<img width="1280" alt="Screen Shot 2023-03-14 at 3 44 07 PM" src="https://user-images.githubusercontent.com/81119399/225159684-c615f676-ba5b-4418-aa8c-82e76767e52e.png">

<img width="1280" alt="Screen Shot 2023-03-14 at 3 44 46 PM" src="https://user-images.githubusercontent.com/81119399/225159698-f69157d2-f1f2-4d64-a974-8914d62ef5c3.png">

An Admin User can delete all background jobs that are in the "pending" state
(newuser is an Admin):

<img width="1280" alt="Screen Shot 2023-03-14 at 3 46 48 PM" src="https://user-images.githubusercontent.com/81119399/225160380-ef31c7c2-cdf6-43d9-8a89-b950811010ab.png">

<img width="1280" alt="Screen Shot 2023-03-14 at 3 47 30 PM" src="https://user-images.githubusercontent.com/81119399/225160391-4e7cc768-46d7-4f8d-94e6-0b5f00b5224e.png">

BackgroundJobs controller RSpec test file:

<img width="1280" alt="Screen Shot 2023-03-14 at 4 03 08 PM" src="https://user-images.githubusercontent.com/81119399/225161186-8cecb147-96e4-42d5-b4ff-e6c0ce6ef6a3.png">

BackgroundJobs request RSpec test file:

<img width="1280" alt="Screen Shot 2023-03-14 at 4 24 57 PM" src="https://user-images.githubusercontent.com/81119399/225164086-98b3b501-0b5d-42ba-96dc-8a4bca37fe6a.png">

2023-03-15 15:36 UTC, micronix requested changes

2023-03-15 15:36 UTC, micronix commented on app/views/background_jobs/index.html.erb
> +          <td><%= job.url %></td>
make this url href so that the user can just click on it to download

2023-03-15 15:36 UTC, micronix commented on app/views/background_jobs/show.html.erb
> +  </div>
If the current_user is admin, show the username of the user that created the background job

2023-03-15 15:36 UTC, micronix commented on app/views/background_jobs/show.html.erb
> +    <h5><strong><%= @background_job.created_at.strftime('%B %d, %Y at %l:%M %p') %></strong></h5>
Add Created:

2023-03-15 15:36 UTC, micronix commented on app/views/background_jobs/show.html.erb
> +    <h5><%= @background_job.url %></h5>
Make this an href

2023-03-15 15:36 UTC, micronix commented on app/views/background_jobs/show.html.erb
> +  </div>
Add Completed At: if the job was completed.

2023-03-15 15:36 UTC, micronix commented on config/routes.rb
resolve the routes merge conflict

2023-03-15 15:36 UTC, micronix commented on spec/factories.rb
> +    url { "Test: URL" }
the url is going to be `https://digitalocean.files.com/123.csv`

2023-03-18 01:26 UTC, Javier-Jimenez-18 commented
New User is an Admin. Index page shows all of the background jobs from all users. If a job status is "completed", the Results URL is displayed, in the index and show pages, as a href link to download the results of the query in a CSV file:

<img width="1280" alt="Screen Shot 2023-03-17 at 5 57 01 PM" src="https://user-images.githubusercontent.com/81119399/226075295-1cf99bf2-8eac-4b5e-a1da-3e105a88da54.png">

If a job status is "completed", the show page displays "Completed At":

<img width="1280" alt="Screen Shot 2023-03-17 at 5 59 54 PM" src="https://user-images.githubusercontent.com/81119399/226075306-255e1e54-0196-4667-b583-5c4b42e6e3d0.png">

Test2 User2 is NOT an Admin. Index page shows only his/her background jobs. If a job status is "completed", the Results URL is displayed, in the index and show pages, as a href link to download the results of the query in a CSV file:

<img width="1280" alt="Screen Shot 2023-03-17 at 6 01 41 PM" src="https://user-images.githubusercontent.com/81119399/226075435-b8d5a882-41bb-4975-a7c4-6311f6e5db27.png">

If a job status is "completed", the show page displays "Completed At":

<img width="1280" alt="Screen Shot 2023-03-17 at 6 02 18 PM" src="https://user-images.githubusercontent.com/81119399/226075443-3a85c9ec-ecee-47c1-ba73-05962fae34a4.png">

For all Users, if a job status is not "completed", "Completed At" is NOT displayed and the "Delete" button is displayed:

<img width="1280" alt="Screen Shot 2023-03-17 at 6 04 08 PM" src="https://user-images.githubusercontent.com/81119399/226075509-3133ec7b-1dae-444f-b25f-6037b4e3810a.png">

2023-03-18 08:33 UTC, Javier-Jimenez-18 commented
Test2 User2 is not an Admin. The User Name is not displayed on the show page:

<img width="1280" alt="Screen Shot 2023-03-17 at 7 40 09 PM" src="https://user-images.githubusercontent.com/81119399/226094616-c40d9146-995e-4a0c-8664-80f740328f2c.png">

New User is an Admin. The User Name of the person that created the job is displayed on the show page:

<img width="1280" alt="Screen Shot 2023-03-17 at 7 42 05 PM" src="https://user-images.githubusercontent.com/81119399/226094686-6d0647b3-59f3-4c83-b7b7-92b0c0736130.png">

All of the test cases PASS in the RSpec request test file when they are run individually:

<img width="1280" alt="Screen Shot 2023-03-18 at 1 16 28 AM" src="https://user-images.githubusercontent.com/81119399/226094761-bb97f5f2-f92d-4e6a-8aec-6fdc853c89f6.png">

2023-03-20 16:03 UTC, merged