Kostik/fix account edit workflow/aact 559
ctti-clinicaltrials/aact-admin pull request #301
Opened 2023-10-04 22:23 UTC by kostik700015

That PR fixes account edit workflow.

Changes applied: 

1. “Database ID” changed to “Database Username”

2. Added a field for email.

3. When we have a success message indicating the user’s information was updated successfully.

4. The password & pass_confirmation fields removed from the devise/registrations/_form.html.erb template.

5. Created a new action in the registrations controller password with a view that is identical to _form.html.erb except that it has only “New Password” “Password Confirmation” and “Current Password”, this form will only be used when the user wants to change their password. Make the route for this action /users/password

6. From /users/edit which is the Edit Profile page,  the link to this password action /users/password added.

![image_2023-10-04_18-11-53](https://github.com/ctti-clinicaltrials/aact-admin/assets/58646723/6ceef438-ba80-4182-8aab-6462c0b40079)
![image_2023-10-04_18-11-29](https://github.com/ctti-clinicaltrials/aact-admin/assets/58646723/cb50a006-8eb3-48d8-818f-1a4ab2de5e20)
![image_2023-10-04_16-39-04](https://github.com/ctti-clinicaltrials/aact-admin/assets/58646723/4f5382bc-00f9-46af-9d19-262f7b1ce61a)

2023-10-06 06:56 UTC, Javier-Jimenez-18 commented on app/controllers/users/registrations_controller.rb
> +      flash.now[:notice] = 'User succesfully updated!'
Keep the "green" flash notice and delete the "red" flash notice (usually means error).

2023-10-06 06:58 UTC, Javier-Jimenez-18 commented on app/controllers/users/registrations_controller.rb
> +      flash.now[:notice] = 'Password succesfully updated!'
Same as above, keep the "green" success message and delete the "red" success message.

2023-10-06 07:03 UTC, Javier-Jimenez-18 requested changes
Good job. Just a couple of small changes. When you make the changes, provide a screenshot of the view page for us to see how it looks.

2023-10-06 17:12 UTC, kholtzman5610 requested changes
I agree with Javier suggestions definitely do those if you haven't already. 

Only thing I would suggest to do is to get the check to pass too. The test that relates to this PR would be this one below:

Failures:
1) Users Sign Up Page sign up - verify new user validations
     Failure/Error: expect(page).to have_field 'user_password'
       expected to find field "user_password" that is not disabled but there were no matches
      ./spec/features/users_sign_up_page_spec.rb:160:in `block (2 levels) in <top (required)>'

Failed examples:
rspec ./spec/features/users_sign_up_page_spec.rb:5 # Users Sign Up Page sign up - verify new user validations

2023-10-09 17:09 UTC, kostik700015 commented
> I agree with Javier suggestions definitely do those if you haven't already.
> 
> Only thing I would suggest to do is to get the check to pass too. The test that relates to this PR would be this one below:
> 
> Failures:
> 
> 1. Users Sign Up Page sign up - verify new user validations
>    Failure/Error: expect(page).to have_field 'user_password'
>    expected to find field "user_password" that is not disabled but there were no matches
>    ./spec/features/users_sign_up_page_spec.rb:160:in `block (2 levels) in <top (required)>'
> 
> Failed examples: rspec ./spec/features/users_sign_up_page_spec.rb:5 # Users Sign Up Page sign up - verify new user validations

Thank you for reviewing, everything is fixed.

2023-10-09 17:09 UTC, kostik700015 commented
> Good job. Just a couple of small changes. When you make the changes, provide a screenshot of the view page for us to see how it looks.

Thank you for reviewing, everything is fixed.
![image_2023-10-09_12-38-30](https://github.com/ctti-clinicaltrials/aact-admin/assets/58646723/0cdce73c-df9d-4931-8f45-8eb44afe399d)

2023-10-12 15:06 UTC, merged