Change AACT_STATIC_FILE_DIR Variable
ctti-clinicaltrials/aact-admin pull request #97
Opened 2021-08-27 18:41 UTC by kholtzman5610

I changed AACT_STATIC_FILE_DIR to Rails.configuration.aact[:static_files_directory] and updated all files I needed to do

- I added the  Rails.configuration.aact[:static_files_directory] in the environments test/production/development
- I removed the mention of AACT_STATIC_FILE_DIR updated with the Rails.configuration.aact[:static_files_directory]
- Visited if the pages worked and folder was created in the right place

2021-09-02 04:34 UTC, micronix reviewed
Looks good, did you run the tests?

2021-09-02 14:07 UTC, kholtzman5610 commented
@micronix yes I had some later on asked Crystal to help me and I understand how everything works now!

2021-09-10 17:52 UTC, crystal-wb requested changes
This looks fine overall. But there is an issue with the directory you used for the test enviroment. We want to keep our test files separate from our normal operation files. Please see my comment about this.

2021-09-10 17:52 UTC, crystal-wb commented on config/environments/test.rb
> +  config.aact = {static_files_directory: "public/static/aact-files"}
This should be changed for tests. We don't want to store temporary test files in the directory with all the other files.

Change the directory to use the tmp folder 'tmp/aact-files'

2021-09-13 19:10 UTC, crystal-wb approved these changes
Looks good

2021-09-13 19:13 UTC, merged