Removed Tagged Terms
ctti-clinicaltrials/aact-admin pull request #98
Opened 2021-08-31 19:34 UTC by kholtzman5610

- Removed TaggedTerms controller

- Removed TaggedTerms model

- Removed TaggedTerms mention from the def self.ids_tagged(tag)in study.rb line 25
   terms=Public::TaggedTerm.terms_for_tag(tag).pluck(:term).uniq

- Testing links on all pages to see if all worked

2021-09-02 04:27 UTC, micronix approved these changes
Looks good

2021-09-10 17:46 UTC, crystal-wb requested changes
I noted an issue with a variable that no longer has value because you removed the line of code that referred to the TaggedTerm model. Please check my comments.

2021-09-10 17:46 UTC, crystal-wb commented on app/models/public/study.rb
>        ids=Public::BrowseCondition.ids_for_terms(terms) + Public::BrowseIntervention.ids_for_terms(terms)
You can't just remove that line. This method is being given a tag, that tag is setting the term variable that is being called in this line `ids=Public::BrowseCondition.ids_for_terms(terms) + Public::BrowseIntervention.ids_for_terms(terms)`
This method will throw an error when called.

Check to see if this method is called anywhere. If it is not called then you can remove it. If it is called then we will need to discuss keeping the TaggedTerm model.

2021-09-10 17:46 UTC, crystal-wb commented on app/models/public/tagged_term.rb
> -
Make sure to check for any calls to the methods in this model. Search for the method names. Note if they are saved to variables.

If there are lots of uses of these methods then we'll want to keep the model. If the methods don't seem to be not used or used very rarely, then we can probably remove the model. Though we will have to fix what was using them.

2021-09-16 23:59 UTC, kholtzman5610 commented
### Update on commit:
- Restored line 25 in ( app/models/public/study.rb )
- Restored TaggedTerms model ( app/models/public/study.rb )

2021-09-17 15:34 UTC, crystal-wb approved these changes
looks good

2021-09-17 15:35 UTC, merged